baseurl = "/"
theme = "casper-two"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "krbysh"
title = "krbysh.net"
disqusshortname = ""
pluralizelisttitles = false
paginate = 6

[permalinks]
post = "/post/:slug/"

[params]
  title       = "krbysh.net"
  subtitle    = ""

  cover       = "img/blog-cover.jpg"
  description = ""
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "krbysh"
  fbName = "krbysh"
  githubName = "krbysh"

  logo = ""
  orgName = "krbysh.net"
  orgWebsite = "https://krbysh.net"
  orgDescription = ""

  author = "krbysh"
  authorAvatar = "img/krbysh.jpg"
  authorLocation = "Tokyo, JP"
  authorWebsite = "https://krbysh.net"
  authorDescription = ""

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Life"
  url = "/categories/life/"
  weight = 100

[[menu.main]]
  name = "Tech"
  url = "/categories/tech/"
  weight = 99
